# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Feed' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Feed

  pod 'FMDB'
  pod 'CMPopTipView'
  pod 'AFNetworking'
  pod 'SDWebImage'
  pod 'MJExtension'
    # pod 'FMDB/FTS'   # FMDB with FTS
    # pod 'FMDB/standalone'   # FMDB with latest SQLite amalgamation source
    # pod 'FMDB/standalone/FTS'   # FMDB with latest SQLite amalgamation source and FTS
    # pod 'FMDB/SQLCipher'   # FMDB with SQLCipher

  target 'FeedTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FeedUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
